### PR TITLE
Add RPCs for external RandomX mining

### PR DESCRIPTION
**Pull request by us77ipis**
### Problem ###
- No external RandomX mining possible.
- Mining multiple algorithms at the same time is currently not possible.
- The algorithm `getblocktemplate` RPC uses for its blocks depends on the value the user selects for mining in the GUI of the wallet / in the config.

### Root Cause ###
Not implemented yet.

### Solution ###
The solution was to:
1. Add an `algo` parameter to the `getblocktemplate` RPC which overrides any mining algorithm specified in the config / GUI.
2. Add a new RPC `rxrpcsb` for submitting randomx blocks, analogous to `pprpcsb`.
This makes it possible to mine at the same time progpow, randomx and sha256d externally, independently of what you may additionally mine using the wallet.

### Bounty PR ###
?

### Bounty Payment Address ##
`sv1qqpjsrc60t60jhaywj5krmwla52ska70twc7wun6qnee65guxhvtxegpqwhuxypra4jn3pq86s24ryltcw6g2ss4573hyqac9u4g23m9mvxpyqqqwny49k`

### Unit Testing Results ###
Tested by mining at the same time progpow blocks with t-rex miner and randomx blocks with xmrig, where both found at least one block.

### CODE REVIEW

**Review by WetOne — APPROVED** [review]

**Comment by WetOne** [comment]
utACK 9974e541fa1074eec0d43fd75371c4431fb9232d

**Review by codeofalltrades — APPROVED** [review]
ACK 9974e541fa1074eec0d43fd75371c4431fb9232d
NIT - Please remove commented out code.

**Comment by us77ipis** [comment]
Now you merged it with the commented code still there?

**Comment by codeofalltrades** [comment]
Yes, I wanted to get it merged. I need to update the copyrights before the release. I will clean this up then if it hasn't been already.

**Pull request merged**
