### PR TITLE
[GUI][QT] Fix "no such slot" and "no matching signal" log errors

### PR DESCRIPTION
**Pull request by CaveSpectre11**
### Problem
Clicking on an address in the Address Book page to pull up the Copy|Edit menu generates "No matching signal" errors in debug.log the first time you use the menu.

### Root Cause
The Qt MetaObject `connectSlotsByName` searches for `connect()` code with slot objects that conform to the format `on_<object-name>_<signal-name>`.  Since the signals for that pulldown (`on_btnCopyAddress_clicked()`, `on_btnEditAddress_clicked()` and `on_btnDeleteAddress_clicked()`) conformed to that format; connectSlotsByName picked them up when they shouldn't have been.

### Solution
Rename these slots in the format `on<Object-name>Clicked` to avoid moc from picking them up inadvertently.

### Additional Scope Included
Several other instances of the same issue were found and corrected in this PR.

_Also included in this PR:_ (https://github.com/Veil-Project/veil/commit/ed31991faf0acddd65e48fe1e22ab06730a5ff5b)
**Problem**
Clicking away from certain pages in the QT wallet generates a "no such slot[...]hideThisWidget()" error in the log file.

**Root Cause**
The fade out logic added to the Settings, Receive and Address Book pages was found on the internet, and the comment of "now implement a slot called hideThisWidget()" was removed and not implemented.   In one instance, an additional "->hide()" call was added. 

**Solution**
Rather than remove the connect for the finish signal, `hideThisWidget()` was implemented in each of the three cases to implicitly hide the widget on the finish signal; and thus provides the infrastructure for further effects to be added in the future if desired.

### Bounty PR
#541 

### Bounty Payment Address
`sv1qqpj9l2f883k7ucs88xdzrcuus8wr6jzrnk85quv3p2u90zwyy6d5tqpq0fl2ksmvlsf5hfddf8ezqnph5q6zf05cmac28g6ytafdzp8aufsuqqqwk9ep3`

### Unit Testing Results
**With v1.0.3 Qt Wallet**
1. Start QT Wallet
2. observe during startup, near the end of loading" connect slots by name errors for the copy address button and the address book button.
```
2019-08-11T14:43:38Z CleanBlockIndexGarbage: Erasing 37481 irrelivant indexes
2019-08-11T14:43:40Z GUI: QMetaObject::connectSlotsByName: No matching signal for on_btnCopyAddress_clicked()
2019-08-11T14:43:40Z GUI: QMetaObject::connectSlotsByName: No matching signal for on_addressBookButton_clicked()
2019-08-11T14:43:48Z New outbound peer connected: version: 70024, blocks=310408, peer=4
```
3. click to the "receive" page
4. click to the "address book" page
5. Observe "no such slot" error when leaving the "receive" page
```
2019-08-11T14:44:42Z GUI: QObject::connect: No such slot ReceiveWidget::hideThisWidget() in qt/veil/receivewidget.cpp:207
2019-08-11T14:44:42Z GUI: QObject::connect:  (receiver name: 'ReceiveWidget')
```
6. click on an address in the address book
7. Observe 3 "no matching signal" errors when the "copy/edit" menu pops up (one for copy, one for edit, and one for delete)
```
2019-08-11T14:45:25Z GUI: QMetaObject::connectSlotsByName: No matching signal for on_btnCopyAddress_clicked()
2019-08-11T14:45:25Z GUI: QMetaObject::connectSlotsByName: No matching signal for on_btnEditAddress_clicked()
2019-08-11T14:45:25Z GUI: QMetaObject::connectSlotsByName: No matching signal for on_btnDeleteAddress_clicked()
```
8. click to the "settings" page
9. Observe "no such slot" error when leaving the "address book" page
```
2019-08-11T14:48:00Z GUI: QObject::connect: No such slot AddressesWidget::hideThisWidget() in qt/veil/addresseswidget.cpp:285
2019-08-11T14:48:00Z GUI: QObject::connect:  (receiver name: 'AddressesWidget')
```
10. click away from the "settings" page
11. Observe "no such slot" error when leaving the "settings" page
```
2019-08-11T14:48:25Z GUI: QObject::connect: No such slot SettingsWidget::hideThisWidget() in qt/veil/settings/settingswidget.cpp:276
2019-08-11T14:48:25Z GUI: QObject::connect:  (receiver name: 'SettingsWidget')
```

** With PR code loaded**
Restart wallet and repeat 1-11 above; observe none of the errors are seen.

### CODE REVIEW

**Comment by CaveSpectre11** [comment]
Closes #541 
Ready for Code Review/QA

**Comment by presstab** [comment]
Hmm this is good to know. I didn't know that it would parse by `on_xx` function naming.

It would also be a good idea if we replaced the old way of connecting signals and slots with the newer function pointer way of doing things, which causes compile time errors for mismatches instead of runtime (although it does not seem like that would have impacted this specific issue addressed in this PR.) Will have to add another issue for that on github.

Nice work!

**Comment by ncrypter90** [comment]
@presstab @CaveSpectre11 
@crypt0-fusi0n 

I can see below error on the log file while opening qt wallet. Is this part of the change? Or can this be ignored?

**2019-09-02T11:33:37Z GUI: QObject::connect: No such slot BitcoinGUI::showDebugWindow() in qt/bitcoingui.cpp:424
2019-09-02T11:33:37Z GUI: QObject::connect: No such slot BitcoinGUI::showDebugWindow() in qt/bitcoingui.cpp:443**

**Comment by CaveSpectre11** [comment]
> I can see below error on the log file while opening qt wallet. Is this part of the change? Or can this be ignored?
> 
> **2019-09-02T11:33:37Z GUI: QObject::connect: No such slot BitcoinGUI::showDebugWindow() 

The scope of the PR was the "no matching signals" that were generated when you copy addresses from the address book; but the missing hideThisWidget slot was an acceptable amount of scope creep, since it was right in those same modules and code flow.

This was not in any means meant to be all encompassing of all missing slots (or even all missing signals).  It was meant to correct the missing signals being called out in the original Issue, and included some extras.  The showDebugWindow() should be a separate issue.

**Comment by ncrypter90** [comment]
Thanks @CaveSpectre11

I will close this as passed. 

@presstab 
@crypt0-fusi0n

**Pull request merged**
