### PR TITLE
[Wallet] Add Transaction Compute Time

### LINKED ISSUE #460: Feature Request: Transaction Compute Time GUI Addition
This is a feature request to add **"Compute Time"** to all local wallet transactions that show up in the wallet GUI. Wallet performance is machine dependent and it is important for users to know how well their machine is performing. Staking and general transaction creation is computationally expensive in Veil and having insight into what is happening in the wallet is vital to keeping users knowledgable about potential issues or slowdowns.

The main driver for this information is the speed of zerocoin spends (and therefore stakes). Veil intends to make zerocoin spends more lightweight and faster in time. Displaying spend times for computationally expensive coins like Veil should be common practice but unfortunately is not. Besides zerocoin, it is still useful to understand how fast or slow the wallet processes/computes different transaction types.

The current method for getting "the approximate amount of time to create a staking block candidate" is calculated comparing the timestamps of certain lines in the debug.log file. 

Subtracting the **"kernel found"** time from the **"AddToWalletIfInvolvingMe"** or **"AddToWallet"** or **"CreateNewBlock: FOUND STAKE!!"** line gives a rough estimate of how long it took the wallet to compute a staking block candidate. Some users have reported times as fast as 4 seconds and others longer than a minute for staking (which means that block is highly likely to orphan)

Proposed Addition Mock-Up:
image

A **"Compute Time"** section should display in the GUI wallet transaction pop-up that displays the time in seconds to 2 decimal places (or milliseconds when compute time is less than 1 second) it took the wallet to compute the transaction. If the transaction is added to the wallet during syncing, the compute Time can display some text suggesting it is not available such as "N/A".

The wallet already gives users some of this information in the debug.log file through time comparisons (End Time Tx -Start Time Tx) and also additionally sometimes already enclosed in print log statements.

 If you use the startup setting **debug=bench** or **debug=blockcreation**, you can get additional information about compute time for most wallet functions.

**debug=blockcreation**
```
2019-03-27T22:12:56Z CreateCoinStake : kernel found
2019-03-27T22:12:58Z GenerateAccumulatorWitness: generating
2019-03-27T22:12:59Z GenerateAccumulatorWitness : 315 mints added to witness
2019-03-27T22:13:06Z CreateNewBlock(): block weight: 51020 txs: 0 fees: 0 sigops 400 Proof-Of-Stake:1 
2019-03-27T22:13:07Z CreateNewBlock: FOUND STAKE!!
 block: 
CBlock(hash=aac02xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx4b9b51ed33ef21f0c, ver=0x20000000, hashPrevBlock=73ba0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx1ba756e8, hashVeilData=541c1b42840a5d34027f54f0ac4e4fd2fbe7b4f7f8e0e60f7667eb81de3e099f, hashMerkleRoot=82685f10c474455b00a03873fc717eba2c452905c8094cf7c205c11500ad6afd, hashWitnessMerkleRoot=82685f10c474455b00a03873fc717eba2c452905c8094cf7c205c11500ad6afd, hashProofOfFullNode=651c1e4854bbea9d34e108abd5faf94c2ea815a5432025aea660baa8d3bd6647, nTime=1553724792, nBits=1a0195b7, nNonce=0, vtx=2)
  CTransaction(hash=b2xxxxx83, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 0358cc0100)
    CScriptWitness()
    CTxOutStandard(nValue=0.00000000, scriptPubKey=)

  CTransaction(hash=a77554cc53, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), scriptSig=c2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx45f2, nSequence=2147484648)
    CScriptWitness()
    CTxOutStandard(nValue=0.00000000, scriptPubKey=)
    CTxOutStandard(nValue=1000.00000000, scriptPubKey=c1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx1f)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx860c)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb0e9f38)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd2b9c2ce)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx4f1498a)

2019-03-27T22:13:10Z [default wallet] AddToWallet b24d6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx29eb6  new
2019-03-27T22:13:10Z UpdateTip: new best=aac0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxf0c height=117848 type=PoS version=0x20000000 tx=3xxx3 date='2019-03-27Txx:xx:xxZ' cache=0.0MiB(291txo)
2019-03-27T22:13:10Z SelectStakeCoins: FOUND 132 STAKABLE ZEROCOINS
2019-03-27T22:13:12Z BitcoinMiner: Tried 3960 stake hashes for block 117849 last=1553724822
2019-03-27T22:13:12Z [default wallet] AddToWallet b24d6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx6029eb6  
2019-03-27T22:13:12Z AddToWalletIfInvolvingMe: detected spent zerocoin in transaction a7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx43 
```

```
2019-03-27T22:13:10Z [default wallet] AddToWallet b24dxxxxxxxxxxxxxxxxxxxxxxx6  new
2019-03-27T22:13:10Z UpdateTip: new best=aac022ebxxxxxxxxxxxxxxxxxxxx1f0c height=117848 type=PoS version=0x20000000 tx=34xxx3 date='2019-03-27Txx:xx:12Z' cache=0.0MiB(291txo)
2019-03-27T22:13:10Z SelectStakeCoins: FOUND 132 STAKABLE ZEROCOINS
2019-03-27T22:13:12Z BitcoinMiner: Tried 3960 stake hashes for block 117849 last=1553724822
2019-03-27T22:13:12Z [default wallet] AddToWallet b24d66a5xxxxxxxxxxxxxxxxxxx6029eb6  
2019-03-27T22:13:12Z AddToWalletIfInvolvingMe: detected spent zerocoin in transaction a775xxxxxxxxxxxxxxxxxxxxxxxxxx31843 
```

**debug=bench**
`2019-03-27T23:48:17Z CreateNewBlock() packages: 10501.60ms (0 packages, 0 updated descendants), validity: 2099.12ms (total 12600.72ms)`
**12.6 seconds**

```
2019-03-27Txx:xx:06Z CreateCoinStake : kernel found
2019-03-27Txx:xx:06Z GenerateAccumulatorWitness: generating
2019-03-27Txx:xx:07Z GenerateAccumulatorWitness : 370 mints added to witness
2019-03-27Txx:xx:15Z     -   CheckTransaction(): 321.02ms
2019-03-27Txx:xx:15Z     -   CheckTransaction(): 320.02ms
2019-03-27Txx:xx:15Z     - Sanity checks: 321.02ms [2.49s (27.70ms/blk)]
2019-03-27Txx:xx:15Z     -   CheckBlock(): 321.02ms
2019-03-27Txx:xx:15Z     - Fork checks: 0.00ms [0.01s (0.10ms/blk)]
2019-03-27Txx:xx:17Z       - Connect 2 transactions: 1389.08ms (694.540ms/tx, 1389.080ms/txin) [61.39s (682.08ms/blk)]
2019-03-27Txx:xx:17Z       - Check zerocoin spends: 1389.08ms
2019-03-27Txx:xx:17Z     - Accumulate zerocoinmints in: 0.00ms
2019-03-27Txx:xx:17Z     - Verify 1 txins: 1390.08ms (1390.080ms/txin) [62.69s (696.61ms/blk)]
2019-03-27Txx:xx:17Z CreateNewBlock() packages: 10501.60ms (0 packages, 0 updated descendants), validity: 2099.12ms (total 12600.72ms)
2019-03-27Txx:xx:17Z     -   CheckTransaction(): 325.02ms
2019-03-27Txx:xx:17Z   - Load block from disk: 0.00ms [0.00s]
2019-03-27Txx:xx:17Z     - Sanity checks: 0.00ms [2.49s (27.40ms/blk)]
2019-03-27Txx:xx:17Z     -   CheckBlock(): 0.00ms
2019-03-27Txx:xx:17Z     - Fork checks: 0.00ms [0.01s (0.10ms/blk)]
2019-03-27Txx:xx:18Z [default wallet] AddToWallet 6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx151  new
2019-03-27Txx:xx:18Z       - Connect 2 transactions: 817.05ms (408.523ms/tx, 817.046ms/txin) [62.20s (683.57ms/blk)]
2019-03-27Txx:xx:18Z       - Check zerocoin spends: 1.00ms
2019-03-27Txx:xx:18Z     - Accumulate zerocoinmints in: 0.00ms
2019-03-27Txx:xx:18Z     - Verify 1 txins: 818.05ms (818.046ms/txin) [63.51s (697.94ms/blk)]
2019-03-27Txx:xx:18Z     - Index writing: 2.00ms [0.34s (3.74ms/blk)]
2019-03-27Txx:xx:18Z     - Callbacks: 0.00ms [0.01s (0.07ms/blk)]
2019-03-27Txx:xx:18Z   - Connect total: 820.05ms [58.09s (638.34ms/blk)]
2019-03-27Txx:xx:18Z   - Flush: 0.00ms [0.01s (0.07ms/blk)]
2019-03-27Txx:xx:18Z   - Writing chainstate: 0.00ms [0.00s (0.03ms/blk)]
2019-03-27Txx:xx:18Z UpdateTip: new best=46xxxxxxxxxxxxxxxxxxxxxxxxf64 height=11xxxx type=PoS version=0x20000000 tx=343478 date='2019-03-xxTxx:xx:xxZ' cache=0.1MiB(831txo)
2019-03-27Txx:xx:18Z   - Connect postprocess: 7.00ms [0.45s (4.93ms/blk)]
2019-03-27Txx:xx:18Z - Connect block: 827.05ms [58.55s (643.39ms/blk)]
2019-03-27Txx:xx:18Z [default wallet] AddToWallet 639a306c52974b113a91f99958d017caf9f5247108dacd14fbfef58adb25d151  
2019-03-27Txx:xx:18Z AddToWalletIfInvolvingMe: detected spent zerocoin in transaction 3411xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8beef104fe1c0 
```

```
2019-03-27T23:05:23Z CreateZerocoinMintTransaction: new mint  DeterministicMint:
   version=2
   count=23356
   hashseed=9axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx2
   hashSerial=cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx39
   hashStake=0b3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx717f71
   hashPubcoin=6cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx88b514
   txid=0000000000000000000000000000000000000000000000000000000000000000
   height=0
   denom=10
   isUsed=0

2019-03-27T23:05:24Z Fee Calculation: Fee:1000000 Bytes:3992 Needed:1000000 Tgt:6 (requested 6) Reason:"Fallback fee" Decay 0.96200: Estimation: (-1 - -1) nan% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+099) 72.01% 0.0/(0.0 0 mem 0.0 out)
2019-03-27T23:05:24Z CommitTransaction:
CTransaction(hash=6cxxxxxxd8, ver=2, vin.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967200), scriptSig=)
    CScriptWitness(8942f6xxxxxxxxxxxxxxxc753addcc401a86f5c3d7bfa292ae466fcad24f8e719776ed94aba2639e342da9dc1ab181defc02f0486c043699e6524491ce3013695cdf3e804e099c8980b782d29c8c64767cc4c72efa79b089adbb5527e235c446777c2d4de2aaff13ae749f4cbe7b8a16b415762de6ad25c221820d9232b6e7fa18d57fb0059439b6d5302927c2e223b3d49b7958eca8e722a2c847fff4aa1d1ab22c50173870bea413887b6aaafdb8e0b69b7a108ac68f51a2267d938f20d3175046178745e952a820c230337707431aad1a87a8152304ec0d7b7e342d9dfe9f25b9b075f9bb17d03e448a5dc3e87c7eb8001267336f3d1467b61b54bd245d5ed20a90fc0f26f79c3cfa9aa2f7906e9fb5771511e8977621deea0584367992d0a5cbc6825d451671e0b0abf31d60cd6c1fd63fe6778f6801ebdb3166fad57381c03d592fcfb73904a87b983f7cecabc84dabf3c99abd23dfd659dca000967e70d2ab83109092011ebd2e80f5db930f0c0ab38058502c906e4c4db40dccdbe93df747ae84253b79d24fd042734f24b44ef528e332a64a5f2bf4bc1f4c309c1495fe5375f323761cad6bbdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd350a7ce8973f0699e8ff8cbb2208e0b4493d2c1ffddf07bf6bb6004a4e81xxxxxxxxxxxx018f3de4d5d5141101e05f7fbd822680abc52a6231e3addbb56b37cdecc128ca487c81c65236ead81daf0ec79df64da455f81025849836636228f5690cbcb1308df69adcd108a3c9a5af8e1f99xxxxxxxxxxxxxxxxxxxxxxx)
    CTxOutData(data=06c0843d)
    CTxOutRingCT(data=036c7b8f350xxxxxxxxxx0a9f434a, pk=027xxxxxxxxxx75979ed5)
    CTxOutStandard(nValue=10.00000000, scriptPubKey=c10280xxxxxxxxxxx55d9ce4)
2019-03-27T23:05:24Z [default wallet] AddToWallet 6cb08fe6dxxxxxxxxxxxxxxxxxxxxx127509e25a9caee469d  new
```

I have gathered some screenshots of the code that I think will be valuable to figuring out how to add this feature to the existing wallet. 

I believe an additional field will need to be added similarly to the nTime field in one of the **Transaction** classes. In particular, the CWalletTx class which has a note that it is:

**"A transaction with a bunch of additional info that only the owner cares about"**

Cwallet Transaction owner cares about

----------------------------
I have added additional code screenshots below that I believe might be useful. 

A deeper dive into the code will reveal what needs to be done to make it work. None of these screenshots contain information on how to display the data, but I am assuming it is readily available where the transaction object is displayed in the GUI pop-up

block creation time

`"2019-03-27T23:48:17Z CreateNewBlock() packages: 10501.60ms (0 packages, 0 updated descendants), validity: 2099.12ms (total 12600.72ms)"`

commit transaction

screenshot1

```
"2019-03-27T22:12:36Z BitcoinMiner: Tried 0 stake hashes for block 117848 last=1553724786
2019-03-27T22:12:54Z SelectStakeCoins: FOUND 133 STAKABLE ZEROCOINS"
```

screenshot2

screenshotComputeTime1

screenshotComputeTime2

time smart based on how or when transaction is created or received

transaction record

I believe this is possibly where a new "compute time" type variable similar to the existing time variable (which is currently for creation time/add to wallet time) can be placed.

wallettx struct

All the Transaction types can be found in the TransactionRecord class:

```
class TransactionRecord
{
public:
    enum Type
    {
        Other,
        Generated,
        SendToAddress,
        SendToOther,
        RecvWithAddress,
        RecvFromOther,
        SendToSelf,
        CTSendToSelf,
        CTSendToAddress,
        CTRecvWithAddress,
        CTGenerated,
        RingCTSendToSelf,
        RingCTSendToAddress,
        RingCTRecvWithAddress,
        RingCTGenerated,
        ZeroCoinMint,
        ZeroCoinSpend,
        ZeroCoinSpendRemint,
        ZeroCoinSpendSelf,
        ZeroCoinRecv,
        ZeroCoinStake,
        ConvertBasecoinToCT,
        ConvertBasecoinToRingCT,
        ConvertCtToRingCT,
        ConvertCtToBasecoin,
        ConvertRingCtToCt,
        ConvertRingCtToBasecoin,
        ConvertZerocoinToCt,
        ZeroCoinMintFromCt,
        ZeroCoinMintFromRingCt
    };
```

This is by no means a finalized request and is flexible. 

The main objective of this feature request is to give users better insight into the amount of time it took their wallets to compute transactions locally. This will help the support team with troubleshooting and can potentially help wallet users diagnose and solve their own problems. Additionally, wallet advancements or slow downs in compute time will be easily noticeable by all users as the wallet evolves.

### PR DESCRIPTION
**Pull request by PeterL73**
- Adds "Show compute time" setting to Wallet Options Dialog
- Adds Compute Time to Wallet Transaction Record and Transaction Details Dialog 

Closes #460

Bounty payment address:
sv1qqp0j5cm6vrrkvkajpnq39gczt09eclw5z8h2zrmvrwndw7ppqaa28spqfqmkpana500t0jmjnhcjekg0rgt9jfll3w03m46p7ard9lqrpxduqqqe9a2qv

### CODE REVIEW

**Comment by Rock-N-Troll** [comment]
image

"ComputeTime" should be replaced with "Compute Time": and "s" should be replaced with "seconds"

**Comment by Rock-N-Troll** [comment]
Additionally, should not be on by default. Should only display in the pop-up with additional checkbox added to the checkbox list here: 
image

Possibly labeled as "Show compute time"

**Comment by Rock-N-Troll** [comment]
My wallet shows compute time of a stake being 18 seconds but I think this is wrong.

I will post the screenshot in place of this text once I am able to.

2019-04-23T0x:xx:51Z SelectStakeCoins: FOUND 2492 STAKABLE ZEROCOINS

**4 seconds**

2019-04-23T0x:xx:55Z CreateCoinStake : kernel found

**12 seconds**

2019-04-23T0x:xx:07Z CreateNewBlock: FOUND STAKE!!

**2 seconds**

2019-04-23T0x:xx:09Z [default wallet] AddToWallet 80xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc2  new


**18 seconds**


However, I think the time that should really be calculated should be maximum 14 seconds as shown per my debug log times above.

**Comment by PeterL73** [comment]
I thought finding a kernel was part of creating a new stake block, that accounts for the difference between the calculated 18 seconds and the expected 14 seconds. However finding the kernel might not be part of creating an new block (matter of opinion), so I moved the ComputeTimeStart as suggested.
Also added the show compute time setting.

**Comment by Rock-N-Troll** [comment]
That's a good point, but in my mind the actual calculation/computation doesn't start until the kernel is found. In the previous implementation , the 2492 other coins in the wallet hat are being hashed for a potential found kernel are all now being factored in as part of the compute time statistic, but that doesn't really make sense. Generally that hashing process takes less than 1 second on most computers though so the end result is usually more or less the same anyway.

**Pull request merged**
