### PR TITLE
[GUI] Removed faq tabs that weren't been used

### PR DESCRIPTION
**Pull request by codeofalltrades**
### Problem ###
There where non used FAQ forms with similar text to the ones than were being used.

### Root Cause ###
Old forms were never deleted.

### Solution ###
Removed old forms and references

### Unit Testing Results ###
View the FAQ tabs
Verify all display
All formatting issues were corrected with #644

### CODE REVIEW

**Comment by MatWaller** [comment]
Looks good to me Code, Thanks.

**Comment by CaveSpectre11** [comment]
needs rebase

**Comment by codeofalltrades** [comment]
rebase complete

**Comment by ncrypter90** [comment]
Observations:
image

hyperlink does not work:
image

Are these issues fixed in #644? if yes then it can be made test passed.
@codeofalltrades @crypt0-fusi0n

**Comment by codeofalltrades** [comment]
Yes the issues noted where fixed in #644

**Pull request merged**
