### PR TITLE
[GUI] Show PoW type for coinbase transactions in transactions history

### PR DESCRIPTION
**Pull request by us77ipis**
* Show the PoW type for each coinbase transaction in the transaction history
  Screenshot from 2022-06-06 15-46-53
* Also implement filtering the transaction history by PoW type

### CODE REVIEW

**Comment by us77ipis** [comment]
Implemented also filtering the transaction history by PoW type.

**Comment by seanPhill** [comment]
On wallet start up, already containing transactions, but not thousands, as it was only created in the past day, the transactions list in the Overview page is blank. There is no message indicating that the wallet might be recalculating the transactions list, **if** it will. I'll leave this wallet running for a few hours, but I'll have to focus on some more urgent PRs now, as these ones missed the release that got released today.

**Comment by us77ipis** [comment]
Did you download the latest build? The (sometimes) empty transaction list problem should be fixed with the latest push from this morning.

**Comment by seanPhill** [comment]
I downloaded this last night. I'll check Github Actions again.

**Comment by seanPhill** [comment]
Great! Thanks! That saved me time getting the latest one, and as this is a new wallet I still have enough of a scrollbar handle that I can still (just) grab it, and scroll back to yesterday, when I did some mining.

RandomX blocks shown yesterday. I'll mine some SHA256D, but I can't mine ProgPow for testing.

**Comment by seanPhill** [comment]
Nice! :)
Screen Shot 2022-06-09 at 1 02 24 pm

**Comment by us77ipis** [comment]
But that screenshot is still not using the latest build, right? It should show "Basecoin mined (...) **on** \<address\>" :thinking:

**Comment by seanPhill** [comment]
Screenshots from a Windows PC mining ProgPow and RandomX. :)
Screenshot_20220609-145903_TeamViewer
Screenshot_20220609-145910_TeamViewer

**Review by Zannick — APPROVED** [review]
utACK 6ad4c7e5c46bec6a1bc049143beb1fd45c0ab50b

**Review by seanPhill — COMMENTED** [review]
All this looks good as it also tested well. I'll give it a *little* more time for other eyes, and for community members with coding experience to get involved.

**Comment by WetOne** [comment]
utACK 6ad4c7e5c46bec6a1bc049143beb1fd45c0ab50b

**Pull request merged**
