### PR TITLE
[GUI] Remove references to x16rt mining algorithm

### PR DESCRIPTION
**Pull request by StrontiumZ38**
### Problem ###
x16rt references are out of date.

### Root Cause ###
Mining algo change

### Solution ###
Update to FAQ entry on mining to reflect algo changes.

### Unit Testing Results ###
Go to Settings -> Frequently Asked Questions -> How do I mine Veil?
image

### CODE REVIEW

**Comment by codeofalltrades** [comment]
I found another referece to x16rt in [/src/qt/veil/forms/settingsfaq09.ui](https://github.com/Veil-Project/veil/blob/c59f70a5399369c844db35e640d7194336141ce3/src/qt/veil/forms/settingsfaq09.ui)

**Comment by codeofalltrades** [comment]
Cherry picked the change from #839.

**Comment by codeofalltrades** [comment]
@CaveSpectre11, @StrontiumZ38 This is ready for review.

**Comment by codeofalltrades** [comment]
Squashed the commits to one.

**Review by CaveSpectre11 — APPROVED** [review]

**Review by CaveSpectre11 — APPROVED** [review]
ACK https://github.com/Veil-Project/veil/pull/838/commits/77cb43888c0252fd7f3de4672758aa8e20c3f864

**Pull request merged**
