### PR TITLE
Connect GUI and RPC to wallet unlockforstaking only flag.

### LINKED ISSUE #315: Console allows for spending while wallet is unlocked for staking only.
> "Hello all, I am not sure who to notify about something I noted when using the GUI wallet in Linux, I have not tried this in any other iteration of the wallet. 
> 
> I found that after having used the upper staking button and entering password for "staking only" per the FAQ's on freshdesk, that I was able to send coins from
> 
> the console with commands without being prompted to enter a password. I did this once accidentally so I tried it again intentionally after locking  + repeating the
> 
> staking unlock procedure and verifying that lock symbol at bottom right indicated locked.
> 
> Could someone else using this same wallet and perhaps others please try and repeat this and notify the proper individuals if I am correct, thanks."

This has been confirmed by Max and Rock-N-Troll. I have no bothered to replicate due to this.

### PR DESCRIPTION
**Pull request by presstab**
closes #315

### CODE REVIEW

**Comment by seanPhill** [comment]
Built Mac GUI of this version.

Unlocked Wallet for Staking, with the slider control on the Settings page.
getwalletinfo reports:
`Staking successfully with "unlocked_until": 0,`
￼
Wallet is successfully winning stakes. 

Wallet cannot do a spend of zerocoins in the Debug Console:
```
spendzerocoin 90 false true 30 tps1qqpaawnsee8an66pf2ekhe9gt77s2cl72gsfwpw7cn06g28v0fqhz8spqwvaljk74rguld73vytvgh5h452n9ltlx00ckdndvpkhk7adenq4wqqqzgv2h9

Error: Please enter the wallet passphrase with walletpassphrase first. (code -13)
```
Tried to spend ten tVeil in the GUI spend page. Nothing happened. (Feedback would be nice.)
Also nothing is found in the debug log.

Stakes are continuing, no problem.

Clicked the 'Unlock Wallet for Staking' slider (into the off position).
Note: The "staking_active" line in getwalletinfo _still shows  "true"_, but staking has stopped, and the lower staking slider is also off.

Spending is still disabled.

Clicking the lower staking slider alerts the user that they need to unlock the wallet before staking can be enabled.

Clicking the upper staking slider brings the pop-up to unlock for staking only. 👍🏻
Unlocking (for staking) confirms with a brief, slow pop up.

Staking has recommenced.

Testing unlocking in the Debug Console:
```
walletpassphrase thePassphraseisnotThis false 120
null
```

Tested the zerocoin spend. Spent, no problem.

_Note: The help text should be changed, to reflect the necessity of the staking only boolean._

The spendzerocoin operation took 101.5 seconds and by the time of my trying the GUI spend the wallet had already locked, and it prompted for the password to unlock for the spend. 👍🏻

The above spend (from GUI) succeeded, as a Sent Zerocoin to Self.

The wallet remains locked afterward. 👍🏻

Testing unlocking via the Debug Console for staking only:
`walletpassphrase ThisisnotmyPassphrase true 123456`

Staking is again succeeding.

**Comment by seanPhill** [comment]
Please note that `"staking_active": true,` (in `getwalletinfo`) is set to true regardless of the staking state, but the GUI staking indicator is correct.

**Comment by presstab** [comment]
@seanPhill Thanks for the feedback. Pushed some additional changes.

- On `getwalletinfo` the staking_active flag is more accurate. It now basically looks if you have tried to stake in the last 0-70 seconds. So there can be a slight delay to this update.
- Add tooltip popup when hovering over the lock icon, which tells if it is locked or if it is unlocked for staking only.
- When sending in the GUI, it now gives the unlock prompt when you try to spend with a wallet that is unlocked for staking only.
- Updated text for the `walletpassphrase` RPC.

**Comment by MisterKangaroo** [comment]
Tested the PR... works good for me on Linux.

But get some errors when i try to compile for windows:

> miner.cpp: In member function ‘std::unique_ptr<CBlockTemplate> BlockAssembler::CreateNewBlock(const CScript&, bool, bool, bool)’:
miner.cpp:142:80: error: no matching function for call to ‘CWallet::CreateCoinStake(uint32_t&, CMutableTransaction&, uint32_t&)’
     if (pwalletMain->CreateCoinStake(pblock->nBits, txCoinStake, nTxNewTime)) {
                                                                            ^
In file included from miner.cpp:28:0:
./wallet/wallet.h:1077:10: note: candidate: bool CWallet::CreateCoinStake(const CBlockIndex*, unsigned int, CMutableTransaction&, unsigned int&)
     bool CreateCoinStake(const CBlockIndex* pindexBest, unsigned int nBits, CMutableTransaction& txNew, unsigned int& nTxNewTime);
          ^~~~~~~~~~~~~~~
./wallet/wallet.h:1077:10: note:   candidate expects 4 arguments, 3 provided
miner.cpp: In function ‘void BitcoinMiner(std::shared_ptr<CReserveScript>, bool, bool)’:
miner.cpp:722:65: error: no matching function for call to ‘std::map<uint256, unsigned int>::count(int&)’
             if (mapHashedBlocks.count(chainActive.Tip()->nHeight)) {
                                                                 ^
In file included from /usr/lib/gcc/x86_64-w64-mingw32/7.3-posix/include/c++/map:61:0,
                 from ./serialize.h:15,
                 from ./script/script.h:11,
                 from ./primitives/transaction.h:11,
                 from ./primitives/block.h:9,
                 from ./miner.h:9,
                 from miner.cpp:6:
/usr/lib/gcc/x86_64-w64-mingw32/7.3-posix/include/c++/bits/stl_map.h:1209:7: note: candidate: std::map<_Key, _Tp, _Compare, _Alloc>::size_type std::map<_Key, _Tp, _Compare, _Alloc>::count(const key_type&) const [with _Key = uint256; _Tp = unsigned int; _Compare = std::less<uint256>; _Alloc = std::allocator<std::pair<const uint256, unsigned int> >; std::map<_Key, _Tp, _Compare, _Alloc>::size_type = long long unsigned int; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = uint256]
       count(const key_type& __x) const
       ^~~~~
/usr/lib/gcc/x86_64-w64-mingw32/7.3-posix/include/c++/bits/stl_map.h:1209:7: note:   no known conversion for argument 1 from ‘int’ to ‘const key_type& {aka const uint256&}’
miner.cpp:724:48: error: no match for ‘operator[]’ (operand types are ‘std::map<uint256, unsigned int>’ and ‘int’)
                 if (GetTime() - mapHashedBlocks[chainActive.Tip()->nHeight] < max(60, 1)) {
                                                ^
In file included from /usr/lib/gcc/x86_64-w64-mingw32/7.3-posix/include/c++/map:61:0,
                 from ./serialize.h:15,
                 from ./script/script.h:11,
                 from ./primitives/transaction.h:11,
                 from ./primitives/block.h:9,
                 from ./miner.h:9,
                 from miner.cpp:6:
/usr/lib/gcc/x86_64-w64-mingw32/7.3-posix/include/c++/bits/stl_map.h:484:7: note: candidate: std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = uint256; _Tp = unsigned int; _Compare = std::less<uint256>; _Alloc = std::allocator<std::pair<const uint256, unsigned int> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = unsigned int; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = uint256]
       operator[](const key_type& __k)
       ^~~~~~~~
/usr/lib/gcc/x86_64-w64-mingw32/7.3-posix/include/c++/bits/stl_map.h:484:7: note:   no known conversion for argument 1 from ‘int’ to ‘const key_type& {aka const uint256&}’
/usr/lib/gcc/x86_64-w64-mingw32/7.3-posix/include/c++/bits/stl_map.h:504:7: note: candidate: std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](std::map<_Key, _Tp, _Compare, _Alloc>::key_type&&) [with _Key = uint256; _Tp = unsigned int; _Compare = std::less<uint256>; _Alloc = std::allocator<std::pair<const uint256, unsigned int> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = unsigned int; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = uint256]
       operator[](key_type&& __k)
       ^~~~~~~~
/usr/lib/gcc/x86_64-w64-mingw32/7.3-posix/include/c++/bits/stl_map.h:504:7: note:   no known conversion for argument 1 from ‘int’ to ‘std::map<uint256, unsigned int>::key_type&& {aka uint256&&}’

**Comment by MisterKangaroo** [comment]
Tooltip on the little lock symbol says 'locked for all types of transactions even if fully unlocked`... beside that it works for me on linux

Ubuntu 18.04

**Pull request merged**
