### PR TITLE
Initial push into C++17 branch

### PR DESCRIPTION
**Pull request by eugene-so**
**Push Summary**
Initial creating of C++17 branch.  

Surgically pull in bitcoin C++17 related changes from 2020-04-11 to 2020-11-18
For now, leave both C++11 and C++17 available as compilation options
Initial goal is to have it compiling successfully on linux, macOS and Windows with whatever updates are required to QT.  
Trying to bring in all important compiler configuration changes and leave the functional code as is except where they are needed to be compatible with C++17 or are blatant surgical improvements.

**Overall Summary (of the branch) **
Problem
Upgrade code base to support C++17 compiler.
Using the updated compiler should hopefully allow us to:

bring in newer module libraries without constantly facing deprecation issues.
use advanced C++17 features
development faster and more effectively
increase compatibility with the bitcoin core
The bitcoin team began the same transition to C++17 in early 2020 as per bitcoin/bitcoin#16684. The majority of changes brought in will be from their repo.

Root Cause
Compilation issues with OSX Catalina impeding progress
Compilation issues with QT5.15 impeding progress
Unable to bring in new versions of Berkely DB (ie. 5.1.29).

Solution
Surgically bring in well-tested migration commits from the bitcoin repo and refactor veil specific code where necessary.

Bounty PR
Bounty Payment Address
sv1qqp6aptgvgp9t9h8sgzkqmu6cgq2e20l9x6fsl5ask7t3ygy2jagftcpq0x5z0h522ca5h06qq3hx33pke00r7gjt3j24n896gf55y68ptrmjqqqqd8lz3

Unit Testing Results
Will try to bring in changes to unit tests where they were updated for bitcoin.

### CODE REVIEW

**Comment by eugene-so** [comment]
This is a good place to pause and review the initial push to this branch as my first objective of getting veil to build on OSX catalina 10.15.7 using Qt 5.15 (on my local system) has been met.  I cherry-picked what look like the essential changes for C++17 from the bitcoin repo between commits 7829685e27aae25efb32e07368175c8f664b2218 and faaee810e62d796d66bfb2bc4e53c8b4c8104d13.  At this point we can optionally compile with C++17 using --enable-c++17.  It still defaults to C++11.  

The next step will be creating an additional CI step to build using macOS 10.14.  We currently build with macOS 10.11.

**Comment by CaveSpectre11** [comment]
@eugene-so we need to separate the CSV code PR #904 from this PR as it confuses the review; especially since there has been another push on that PR.  I'm not sure the best way to remove it, I know you can create a new branch off latest master and cherry pick each of these commits in (minus the CSV code work), but there may be a better way.

**Comment by eugene-so** [comment]
Should be cleared up once the CSV PR is merged. I think this branch was created one commit off and that's why the CSV one shows up as the first commit.
________________________________

**Comment by CaveSpectre11** [comment]
> Should be cleared up once the CSV PR is merged. I think this branch was created one commit off and that's why the CSV one shows up as the first commit.

Yes; however it holds this PR from being able to be merged into the C17++ branch because it includes that other PR (as well as the OSX changes one), neither of which this PR is dependent on; so it makes for a much longer review cycle.  If you remove those from this it can be contained to the intent of the PR and not have 'extra stuff' in it.

The commits in the PR should be what's described in the PR, and if it is dependent on other PRs, that should be mentioned as well. (E.g. see #879 )

**Comment by eugene-so** [comment]
> > Should be cleared up once the CSV PR is merged. I think this branch was created one commit off and that's why the CSV one shows up as the first commit.
> 
> Yes; however it holds this PR from being able to be merged into the C17++ branch because it includes that other PR (as well as the OSX changes one), neither of which this PR is dependent on; so it makes for a much longer review cycle. If you remove those from this it can be contained to the intent of the PR and not have 'extra stuff' in it.
> 
> The commits in the PR should be what's described in the PR, and if it is dependent on other PRs, that should be mentioned as well. (E.g. see #879 )

I can see if I can rework the PR so it is independent of the CSV PR.  However, I would argue that the OSX is part of this as getting it to compile properly on Catalina was what triggered this branch to be created in the first place.  I can't remember anymore, but maybe a PR for the first OSX change (commit 
46b47ca) may be sufficient for the first PR into this branch.  That way we start off with a smaller chunk.

**Comment by eugene-so** [comment]
Please merge PR #959 first to rebase the base c++17 branch.

**Comment by eugene-so** [comment]
Already merged a later PR #961

**Pull request closed without merging**
