### PR TITLE
[WIP] [Wallet] [QT] Custom automint delay time.

### LINKED ISSUE #433: Allow Automint interval to be user selectable
Add a time option to automint in the GUI to allow the user to select how frequent automint should do it's thing

### PR DESCRIPTION
**Pull request by veildev**
Closes #433

### CODE REVIEW

**Comment by furszy** [comment]
good catch.

**Comment by blondfrogs** [comment]
Closes #433

**Comment by crypt0-fusi0n** [comment]
@presstab Hey, what's happening with this one? Does it need QA?

**Comment by presstab** [comment]
Closing this as stale.

**Pull request closed without merging**
