### PR TITLE
Fix errors compiling for OSX catalina

### PR DESCRIPTION
**Pull request by eugene-so**
Push Summary
Fix compilation issue on MacOS 10.15 Catalina machine.

Root Cause
Changes in XCode 11 Objective-C Runtime caused an error building on
MacOS 10.15 Catalina machine.  
Updated instruction on how to build berkeley DB for macOS 10.15 Catalina.

Solution
Ported solution from bitcoin PR 16720.

Bounty PR
Bounty Payment Address
sv1qqp6aptgvgp9t9h8sgzkqmu6cgq2e20l9x6fsl5ask7t3ygy2jagftcpq0x5z0h522ca5h06qq3hx33pke00r7gjt3j24n896gf55y68ptrmjqqqqd8lz3

Unit Testing Results

### CODE REVIEW

**Review by CaveSpectre11 — APPROVED** [review]
utACK https://github.com/Veil-Project/veil/pull/940/commits/1f03f54d37c152416d8785584044e52ecb4c7b41

**Comment by seanPhill** [comment]
Seem to have a problem with Boost on a fairly fresh Catalina MacBook Pro.
```
cd depends
make
```
...
Fetching boost_1_64_0.tar.bz2 from https://dl.bintray.com/boostorg/release/1.64.0/source/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
Fetching boost_1_64_0.tar.bz2 from https://bitcoincore.org/depends-sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76.7M  100 76.7M    0     0   157k      0  0:08:19  0:08:19 --:--:--  378k
/Users/.../Documents/GitHub/veil/depends/work/download/boost-1_64_0/boost_1_64_0.tar.bz2.temp: OK
Extracting boost...
/Users/.../Documents/GitHub/veil/depends/sources/boost_1_64_0.tar.bz2: OK
Preprocessing boost...
Configuring boost...
Building Boost.Build engine with toolset darwin... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
make: *** [/Users/.../Documents/GitHub/veil/depends/work/build/x86_64-apple-darwin19.6.0/boost/1_64_0-0bee59b2cae/./.stamp_configured] Error 1

**Comment by eugene-so** [comment]
Hmmm... Sorry.  I never used make depends locally. Is it working now with cave spectre's push?
________________________________

**Comment by seanPhill** [comment]
I got a checksum error on the first download, so it downloaded from the bitcoin repo and got a checksum error also.

**Comment by eugene-so** [comment]
Let's talk about this for a minute.  It now looks like Cave Spectre's change broke the automated build check (which was working previously).  In this PR, I never touched the dependent boost library or the automated build macOS version.  It was meant to fix a local build on MacOS Catalina which is what I'm using.

I usually build using these commands which are described in build-osx.md:
```CFLAGS="-Wno-error=implicit-function-declaration"  ./contrib/install_db4.sh .
export BDB_PREFIX=‘$(pwd)/db4'
./autogen.sh
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
make -j4
```

As such I never tested
```make depends```
on my local machine.  Why do you need to compile it like this?  Are you able to compile it using the same commands as me?

**Comment by CaveSpectre11** [comment]
> Let's talk about this for a minute. It now looks like Cave Spectre's change broke the automated build check (which was working previously). 

Since you didn't build depends; we don't know if bintray.com going down is what broke depends, or if depends doesn't build on Catalina.  So this was an attempt to isolate the problem.   Since Sean is able to test it, this seemed like a good place to put that change quickly so that he doesn't have to monkey around with cherry-picking together two different branches.

It's been reverted since boost.org had a bad checksum on their website.

**Comment by eugene-so** [comment]
> It's been reverted since boost.org had a bad checksum on their website.

What shall we do here then?  I know that later in the C++17 branch I do start updating the boost library and automated build osx versions.

**Comment by seanPhill** [comment]
On Catalina, using the documented in build-osx.md brew install ... method `depends` installed fine. Carefully checked afterward. (Also successful on Big Sur and High Sierra.)

When compiling afterwards, with 
```
 ./autogen.sh
 ./configure
 make
```
Everything seemed to be going fine when suddenly getting 20 errors apparently relating to C++17, hitting the maximum errors and then stopping.

I've copied and pasted the output from around the point that the errors began.

[Catalina-veil-install-errors-20210507.pdf](https://github.com/Veil-Project/veil/files/6442387/Catalina-veil-install-errors-20210507.pdf)

**Comment by eugene-so** [comment]
> On Catalina, using the documented in build-osx.md brew install ... method `depends` installed fine. Carefully checked afterward. (Also successful on Big Sur and High Sierra.)
> 
> When compiling afterwards, with
> 
> ```
>  ./autogen.sh
>  ./configure
>  make
> ```
> 
> Everything seemed to be going fine when suddenly getting 20 errors apparently relating to C++17, hitting the maximum errors and then stopping.
> 
> I've copied and pasted the output from around the point that the errors began.
> 
> [Catalina-veil-install-errors-20210507.pdf](https://github.com/Veil-Project/veil/files/6442387/Catalina-veil-install-errors-20210507.pdf)

Hmmm... peculiar. I thought I had it compiling on my Catalina system without requiring C++17 at this point.  I'll give it another try from scratch build as well.

**Comment by eugene-so** [comment]
Ok, I found that this was actually missing one cherry-pick related to dark mode that is required.  It now compiles fine on my Catalina system from scratch.  @seanPhill : I wonder if there is a mismatch on your system between the QT@5 installed using brew as a dependency and another version of QT on your system?  On my system, I do not have the path /usr/local/include/QtCore where your error is showing up.  Instead I have /usr/local/Cellar/qt\@5/5.15.2/include/QtCore which is the one installed by brew.

**Comment by eugene-so** [comment]
brew info qt@5
qt@5: stable 5.15.2 (bottled) [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt@5/5.15.2 (10,688 files, 367.9MB)
  Poured from bottle on 2021-04-11 at 12:07:56
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/qt@5.rb
License: GFDL-1.3-only and GPL-2.0-only and GPL-3.0-only and LGPL-2.1-only and LGPL-3.0-only
==> Dependencies
Build: pkg-config ✔
==> Requirements
Build: Xcode ✘
Required: macOS >= 10.12 ✔
==> Caveats
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

qt@5 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have qt@5 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> ~/.profile

For compilers to find qt@5 you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt@5/lib"
  export CPPFLAGS="-I/usr/local/opt/qt@5/include"

For pkg-config to find qt@5 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"

==> Analytics
install: 52,393 (30 days), 142,535 (90 days), 142,565 (365 days)
install-on-request: 4,985 (30 days), 11,022 (90 days), 11,052 (365 days)
build-error: 0 (30 days)

**Comment by eugene-so** [comment]
On another note, I wonder why it is pulling the QT5 include from the wrong place?

**Comment by seanPhill** [comment]
I have the same qt@5 result that you have. I don't know why an error would refer to a different file path.
```
 brew info qt@5
qt@5: stable 5.15.2 (bottled) [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt@5/5.15.2 (10,688 files, 367.9MB)
  Poured from bottle on 2021-04-09 at 11:35:54
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/qt@5.rb
License: GFDL-1.3-only and GPL-2.0-only and GPL-3.0-only and LGPL-2.1-only and LGPL-3.0-only
==> Dependencies
Build: pkg-config ✔
==> Requirements
Build: Xcode ✔
Required: macOS >= 10.12 ✔
``` (Caveats & analytics are identical.)

**Comment by eugene-so** [comment]
Yes, you have the same  brew installed version, but what I mean is the error you posted earlier shows that the compiler is using a different QT on your system.  We'll probably have to look into how to fix this to make sure it is using ***@***.*** even if a different QT is installed.

________________________________

**Comment by eugene-so** [comment]
Please just try a quick test... If you rename your directory /usr/local/include/QtCore to something else for you still get the same error?
________________________________

**Comment by seanPhill** [comment]
I really don't think that is the issue. ` /usr/local/include/QtCore` is a symlink to `QtCore -> ../Cellar/qt/6.0.3_2/include/QtCore`
There's _are dozens of_ Qt-related symlinks in there, including `QtCore5Compat -> ../Cellar/qt/6.0.3_2/include/QtCore5Compat`

In fact it was the `brew install ... qt ...` that installed this version. A few weeks earlier on a different coin qt@5 was installed for those depends. It's not entirely in scope for this PR, but I have a High Sierra Mac that had neither installed and I have installed qt@5 on it. (I think qt@6 might not be High Sierra compatible.) I will try the installation on that one for the moment, although being out of support there might be other issues.

**Comment by eugene-so** [comment]
I'm pretty sure the different qt headers is the issue and it should be fixed on the makefile side.  Just thought it might be easy for you to test without the extr a qt, but I'll can also try to reproduce your issue when I have some time. Had a ton of family medical issues lately unfortunately. 😔
________________________________

**Comment by seanPhill** [comment]
No worries. FYI, the High Sierra Mac that I specifically made sure that `brew install qt@5` instead of `brew install qt` *did* correctly compile, without problems.

**Comment by seanPhill** [comment]
On a Catalina Mac I removed qt@6 and pyqt that depends on it, and tried to compile, but I got an error relating to files written with an older version of protoc. `brew info protobuf` shows 'stable 3.15.8'. I'm guessing that some other dependencies other than qt@5 should be specified (in brew install ...) as not the latest.
[protobuffer-error.pdf](https://github.com/Veil-Project/veil/files/6447751/protobuffer-error.pdf)

**Comment by eugene-so** [comment]
> On a Catalina Mac I removed qt@6 and pyqt that depends on it, and tried to compile, but I got an error relating to files written with an older version of protoc. `brew info protobuf` shows 'stable 3.15.8'. I'm guessing that some other dependencies other than qt@5 should be specified (in brew install ...) as not the latest.
> [protobuffer-error.pdf](https://github.com/Veil-Project/veil/files/6447751/protobuffer-error.pdf)

The brew version 3.15.8 seems correct.  What do you get when you type this command?

```
protoc --version
```

I get libprotoc 3.15.8

**Comment by eugene-so** [comment]
Seems like bitcoin eventually completely dropped protobuf from their build

**Comment by eugene-so** [comment]
What is happening with this PR?  Seems like something broke with the automated build recently?

**Comment by seanPhill** [comment]
I can approve the automated build again now. I see it is waiting.

**Review by codeofalltrades — CHANGES_REQUESTED** [review]
I think the CPPFLAGS changes need to appear in the yml files used by gitian
https://github.com/Veil-Project/veil/blob/master/contrib/gitian-descriptors/gitian-linux.yml

**Comment by eugene-so** [comment]
> I think the CPPFLAGS changes need to appear in the yml files used by gitian
> https://github.com/Veil-Project/veil/blob/master/contrib/gitian-descriptors/gitian-linux.yml

This change should not impact the linux build.  
I reviewed gitian-osx.yml and there are no CPPFLAGS in that one.  Do you know how I can test the gitian build process to make sure it is working?

**Review by codeofalltrades — APPROVED** [review]
utACK d596243fb857373a1024087d25fe04e21ae3be7f

**Pull request merged**
