### PR TITLE
[GUI] Add transaction list filtering

### LINKED ISSUE #540: GUI Enhancement: Add "Filter By" And Cascade The Selection With "Sort By" In Transactions List
image

A cascading filter for "Filter By" in connection with "Sort By" should be added for further filtering of the Transactions List View.

`Filter By` should filter by transaction types (listed below) which can be found in the `TransactionRecord` class:

image

**--Send _(Wherever there is RED text in the transaction list)_
--Receive _(Wherever there is GREEN text in the transaction list)_
--Mint
--Stake
--Basecoin
--CT
--RingCT
--Zerocoin _(Always with --Mint and --Stake)_**
```
class TransactionRecord
{
public:
    enum Type
    {
        Other,						--???
        Generated,					--???
        SendToAddress,					--Receive
        SendToOther,					--Send
        RecvWithAddress,				--Receive
        RecvFromOther,					--Receive
        SendToSelf,					--Receive                                              
        CTSendToSelf,					--CT --Receive                      
        CTSendToAddress,				--CT --Send
        CTRecvWithAddress,				--CT --Receive
        CTGenerated,					--CT --Receive
        RingCTSendToSelf,				--RingCT --Receive
        RingCTSendToAddress,				--RingCT --Send
        RingCTRecvWithAddress,				--RingCT --Receive
        RingCTGenerated,				--RingCT --Receive
        ZeroCoinMint,					--ZeroCoin --Mint --Receive
        ZeroCoinSpend,					--ZeroCoin --Send
        ZeroCoinSpendRemint,				--ZeroCoin --Mint --Receive
        ZeroCoinSpendSelf,				--ZeroCoin --Send
        ZeroCoinRecv,					--ZeroCoin --Receive
        ZeroCoinStake,					--ZeroCoin --Stake --Receive
        ConvertBasecoinToCT,				--CT --Basecoin --Receive
        ConvertBasecoinToRingCT,			--CT --RingCT --Receive
        ConvertCtToRingCT,				--CT --RingCT --Receive
        ConvertCtToBasecoin,				--CT --Basecoin --Receive
        ConvertRingCtToCt,				--CT --RingCT --Receive
        ConvertRingCtToBasecoin,			--RingCT --Basecoin
        ConvertZerocoinToCt,				--CT --ZeroCoin --Receive
        ZeroCoinMintFromCt,				--CT --Zerocoin --Mint --Receive
        ZeroCoinMintFromRingCt				--RingCT --Zerocoin --Mint --Receive
    };
}
```

I may have mis-attributed some of these filters because I based them on my interpretation of their English naming instead of determining their actual use.

I am also unsure what **Other** and **Generated** apply too so left them empty for now. Part of this task is to also ensure the correct filter attributes are setup correctly.

### PR DESCRIPTION
**Pull request by MatWaller**
Adding filtering functionality to the transactions list.

Closes #540 

Transactions can now be filtered using the Taxonomies;
- Sent
- Received
- Mint
- Mined
- Stake
- Basecoin
- RingCT
- CT
- ZeroCoin
- All

Screenshot from 2019-05-11 03-47-43
aaa

Bounty Address
```
sv1qqpdsfcqvfcljtcq8txc8kc2dw4e9upj69wnnfv7j0ufcsrv7trs9lqpqfscke6jj92aj4aup387ggk7mathznr8hz3zde6ut87jdwphrns7qqqq00jn8w
```

### CODE REVIEW

**Comment by crypt0-fusi0n** [comment]
A couple of minor things... please correct. Thanks

image

**Comment by MatWaller** [comment]
@crypt0-fusi0n 

Typo Corrected & added a 20px buffer to the filter combo box.

**Comment by MatWaller** [comment]
Thanks :+1:

**Comment by gabrielnergaard** [comment]
"Filter Type" and "Sort" should be list headings. They should not be items in the enumerated list of selectable items themselves.

**Comment by MatWaller** [comment]
As with a "select" element on a Web page this is fairly common.

There isn't really enough space to put headings for each box without
causing clutter, just my thought of course.

**Comment by gabrielnergaard** [comment]
I don't think it's common in web forms to use an element of a select field as the label. But I do see what you mean about not having space there to put a label.

Horizontally, there might be enough room to do make the default and first selected item in the filter list "Show All" to communicate the function of the selector (and then leave the rest of the entries as they are, since contextually they'll be understandable as labels when selected.)

If you took this approach, then the Sort menu would have only two items: "Sort by Date" and "Sort by Amount".

Personally, I think this would be sharper and more precise UI, but it might not be a big enough deal to be worth the effort (unless you strongly agree with what I'm proposing, and if it were trivial to change.)

**Comment by MatWaller** [comment]
Wouldn't imagine it's a big task, I'm happy to put something together and
see how it looks.

**Pull request merged**
