### PR TITLE
[Qt] Update pay amount text box

### LINKED ISSUE #488: Miscellaneous GUI/Display Bugs: Send Screen
In the send screen, it is impossible to send any value in the last decimal place. Attached is a screenshot that shows the last digit not being populated after trying to put in the maximum number of characters possible into the main screen as shown in the top right of the screenshot.

image

This is an extra issue that is probably not GUI related, but an empty error message pop-up can happen when using odd (but should still be possible) decimal places:
image

Additionally, it looks like commas are allowed to be entered but don't work at all anyway.

image

image

Miscellaneous error messages
```
2019-04-10T00:00:15Z ERROR: ringctwallet AddStandardInputs_Inner: Failed to calc fee
2019-04-10T00:00:15Z ERROR: CreateZerocoinSpendTransaction: AddStandardInputs failed: 
2019-04-10T00:00:15Z ERROR: PrepareZerocoinSpend : Failed to add standard inputs
```

### PR DESCRIPTION
**Pull request by blondfrogs**
- Allow for 8 decimals instead of the current 7
- Remove commas from being added to the amount

Closes #488

### CODE REVIEW

**Comment by ncrypter90** [comment]
Bug:
The send option will not allow amount with decimal more than 7.

image

**Comment by blondfrogs** [comment]
@ncrypter90 I need more information on how you tested this. Operation System?

**Comment by blondfrogs** [comment]
Tested via Linux: 
image

**Comment by ncrypter90** [comment]
@blondfrogs i have tested on Windows :
image

image

**Comment by ncrypter90** [comment]
one more update one the issue:
Veil_build_517_Screengrab

**Comment by blondfrogs** [comment]
@ncrypter90 This is making me think that the windows build isn't working correctly as it is also allowing commas into the amount text box, which is also removed in this commit

**Comment by blondfrogs** [comment]
@ncrypter90 As far as the failure to send prompt. I believe that was resolved in a different issue. That veil client automatically grabs funds from the available Zerocoin, Ringct, ct, and basecoin. And some of the spends weren't calculating the fee correctly resulting in a failure to create the transaction. I am currently building a windows executable with the latest master branch, with this commit pulled into it. This will let us figure out if it is an issue with the windows build, or the code itself.

**Comment by ncrypter90** [comment]
QA Update:
Code change for below : works fine on Win 10,Mac and Ubuntu.

Allow for 8 decimals instead of the current 7
Remove commas from being added to the amount

**Pull request merged**
