### PR TITLE
[Qt] Add mouse leave event to balance buttons.

### LINKED ISSUE #202: Feature request: Balance breakdown to remain visible until I move the mouse away.
Clicking the (?) next to Total Balance reveals the Zerocoin, RingCT and Basecoin breakdown.

**I wish that** it would remain until I move the mouse away, or have some other way of being viewed. It is very annoying to continually have to relaunch that little bit of information while contemplating how much is in each category.  

Veil macOS wallet v1.0.0.5 self-compiled.

This is a feature request.

### PR DESCRIPTION
**Pull request by drag0ng**
Fixes #202

### CODE REVIEW

**Comment by xo-orca** [comment]
Hi drag0ng,
As per #202, the original behaviour is that the breakdown box lasts for only 5 sec before it disappears.
The suggested behaviour is that the breakdown box disappears only on the "mouse leave" event.
On Linux, although the mouse still on the buttons (hasn't moved yet) it is still disappearing after the 5 sec, 

Not tested on Mac yet.

Thanks,
xo.

**Comment by drag0ng** [comment]
I should remove the timer in the tooltip

**Comment by crypt0-fusi0n** [comment]
@xo-orca new (linux and mac) builds ready in a few hours... Windows still has issues.

**Comment by crypt0-fusi0n** [comment]
> @xo-orca new (linux and mac) builds ready in a few hours... Windows still has issues.

New builds ready in the usual location. Please test.

**Comment by xo-orca** [comment]
Hi drag0ng, 

The 5sec timer is now gone.

The "mouse leave" event is now working on the "unconfirmed" and the "immature" for the caption as well as the question mark icons. 

For the "Total balance," although the caption is working fine, the question mark icon is not.

Noe, clicking on the question mark next to the "Total balance" doesn't display the tip box as expected.
for some reason, you have to click a couple of times or more to display the tip box.
Also, the "mouse leave" event, it is not working on the question mark next to the "Total balance" 

xo.

**Comment by crypt0-fusi0n** [comment]
Hi @drag0ng , what's the status on this one? Thanks

**Comment by drag0ng** [comment]
mouseleave1

**Pull request merged**
