### PR TITLE
fix address generation button in wallet receive tab

### LINKED ISSUE #509: GUI Bug: Generate Address Icon doesn't work
Clicking the "Generate Address" circle arrow icon in the bottom left of the Receive screen shows a pop up for "address generated" but it doesn't do anything

image

but the debug log shows:

> 
> 2019-04-13T22:06:13Z GUI: QObject::connect: No such slot AddressesWidget::hideThisWidget() in qt/veil/addresseswidget.cpp:283
> 2019-04-13T22:06:13Z GUI: QObject::connect:  (receiver name: 'AddressesWidget')
> 2019-04-13T22:06:15Z GUI: QObject::connect: No such slot ReceiveWidget::hideThisWidget() in qt/veil/receivewidget.cpp:203
> 2019-04-13T22:06:15Z GUI: QObject::connect:  (receiver name: 'ReceiveWidget')
> 2019-04-13T22:06:18Z GUI: QObject::connect: No such slot AddressesWidget::hideThisWidget() in qt/veil/addresseswidget.cpp:283
> 2019-04-13T22:06:18Z GUI: QObject::connect:  (receiver name: 'AddressesWidget')
> 
>

### PR DESCRIPTION
**Pull request by rikublock**
This PR resolves two things.
- Adds missing QT slots that were initially believed to be the cause of the address generation issue (although the issue occurred in receivewidget.cpp, several similar slots were also missing in other widgets and have been added with this PR)
- Resolves the root cause of the address generation bug. Currently, the latest address generated in the GUI wallet is labeled "stealth". If an address with that label already exists, no additional addresses are generated.  The issue is resolved by removing the label of the old address in order to allow the generation of a new address with the "stealth" label.

resolves #509

### CODE REVIEW

**Comment by ncrypter90** [comment]
QA FAILED!

"Generate Address" circle arrow icon is missing in the bottom left of the Receive screen shows a pop up for "address generated"

As build note says "**If an address with that label already exists, no additional addresses are generated. The issue is resolved by removing the label of the old address in order to allow the generation of a new address with the "stealth" label.**" doesn't work as explained.

Screen Shot 2019-07-03 at 7 30 38 pm

**Comment by rikublock** [comment]
So, can I conclude from your comment that you didn't review nor test the actual code in the PR as you were already unable to find the UI button ?

**Comment by ncrypter90** [comment]
Its not just about UI button, receive address is not being replaced by new. instead it will generate new address with label stealth , so you will see two addresses with label stealth in address list. Receive stealth address remain same as old.

**Comment by CaveSpectre11** [comment]
Overcome by Events: #652

**Pull request closed without merging**
