### PR TITLE
[GUI] Updating & Simplifying Formatting/Styling of Content.

### LINKED ISSUE #548: GUI Enhancements: Make modal, popup & window styling consistant & uniform.
## The Problem.
At present modals, popups & windows sizing, spacing & overall style is inconsistent & non uniform with many instances of repetition within the styling itself [Inline styling] -- This makes for a confusing user experience & bit of a developer headache when re-skinning/restructuring the application when the new UI/UX is good to go.

## Current modals, popups & windows
learn
options
pass
sync

## The Solution.

1. Move in-line styling into a set of common `qss` as to allow for easier/cleaner development and management of the style & layout moving forward (While also reducing the amount of code needed for styling)
2. Update styling & layouts as so sizing, spacing etc.. is uniform and consistent throughout the wallet.

### PR DESCRIPTION
**Pull request by MatWaller**
- Updating FAQ tabs as so the content is only being set in one place.
- Added Titles to each tab.
- Added links to the contents (bitcointalk post & veil bounty program)
- Ensured formatting was uniform.
- Removed " " that encapsulated the content on some tabs.
- Replaced unparsed HTML entities.
- Removed unusual border from password unlock model.

clean

closes #548

### CODE REVIEW

**Comment by crypt0-fusi0n** [comment]
Couple of issues with this one...

1. Font not consistent on mac
2. Clicks not clickable. Nothing happens when clicked.

veilFAQ
veilFAQmac

**Comment by MatWaller** [comment]
@crypt0-fusi0n thanks for the feedback will correct outstanding issues later today.

**Comment by crypt0-fusi0n** [comment]
Let me know how you go @MatWaller ... if you need a bit of time, I might close this PR and just submit a new PR when you're ready...

**Comment by crypt0-fusi0n** [comment]
@MatWaller It's been 14 days... please submit new PR

**Comment by codeofalltrades** [comment]
I can clean this one up.

**Comment by codeofalltrades** [comment]
@MatWaller - Please give this a review also.

**Comment by MatWaller** [comment]
Taking a look now.

**Comment by codeofalltrades** [comment]
Rebase complete

**Comment by codeofalltrades** [comment]
> needs conflicts resolved

Done

**Comment by mimirmim** [comment]
Can this be merged in please.

**Comment by MatWaller** [comment]
Looks like the Travis build timed out, i have re-queued it.

**Comment by ncrypter90** [comment]
Looks good , I will mark it passed, however, an observation on the font size of the headline:
image

**Comment by codeofalltrades** [comment]
Resolved a conflict. Waiting for Travis to finish before I merge it.

**Comment by MatWaller** [comment]
@ncrypter90 Ill take a look at the font size on that page and make a separate PR.

**Pull request merged**
